<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>63f1d0ec-a4c5-4430-ab21-b858ce946dc6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GenAI.Application\GenAI.Application.csproj" />
    <ProjectReference Include="..\GenAI.Infrastructure\GenAI.Infrastructure.csproj" />
  </ItemGroup>

</Project>